name: Discord Alerts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enviar alerta para o Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: " Novo commit ou PR criado no repositório!"
